#!/bin/bash
# code-docs.sh - Entry-point for the code-docs build system
#
# Usage:
#   ./code-docs.sh setup          Interactive .env wizard
#   ./code-docs.sh up             Start Docker container (auto-setup if no .env)
#   ./code-docs.sh up --clean     Clean output files, then start Docker container
#   ./code-docs.sh down           Stop Docker container
#   ./code-docs.sh status         Show container state and configuration
#   ./code-docs.sh logs           Follow container logs (Ctrl+C to stop)
#   ./code-docs.sh help           Usage info

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd -P)"

# --- Helper functions ---

load_env() {
    if [[ -f "$SCRIPT_DIR/.env" ]]; then
        # shellcheck disable=SC1090
        source "$SCRIPT_DIR/.env"
        # Export vars so docker compose picks them up for interpolation in docker-compose.yml.
        # Shell env vars take precedence over the .env file that docker compose also reads,
        # ensuring $HOME and other shell expansions are resolved correctly.
        export CODE_DIR="${CODE_DIR:-}"
        export OUTPUT_DIR="${OUTPUT_DIR:-}"
        export EXCLUDE_PROJECTS="${EXCLUDE_PROJECTS:-}"
        export SIDEBAR_STYLE="${SIDEBAR_STYLE:-tree}"
        export HTTP_PORT="${HTTP_PORT:-8000}"
        return 0
    fi
    return 1
}

check_deps() {
    if ! command -v docker &>/dev/null; then
        echo "Error: docker is not installed or not in PATH."
        echo "Install Docker Desktop: https://www.docker.com/products/docker-desktop"
        return 1
    fi
    if ! docker compose version &>/dev/null 2>&1; then
        echo "Error: 'docker compose' plugin not found."
        echo "Install Docker Desktop: https://www.docker.com/products/docker-desktop"
        return 1
    fi
    return 0
}

run_compose() {
    (cd "$SCRIPT_DIR" && docker compose "$@")
}

container_running() {
    run_compose ps --quiet --status running 2>/dev/null | grep -q .
}

# --- Subcommand functions ---

cmd_setup() {
    echo "=== code-docs setup ==="
    echo ""

    if [[ -f "$SCRIPT_DIR/.env" ]]; then
        echo "Current .env configuration:"
        echo ""
        while IFS= read -r line; do
            if [[ -n "$line" && "$line" != \#* ]]; then
                echo "  $line"
            fi
        done < "$SCRIPT_DIR/.env"
        echo ""
        read -rp "Reconfigure? [y/N] " answer
        if [[ ! "$answer" =~ ^[Yy] ]]; then
            echo "Keeping existing configuration."
            return 0
        fi
        echo ""
    fi

    # --- CODE_DIR ---
    local default_code="$HOME/Documents/code"
    echo "1) CODE_DIR — Directory containing source code projects"
    read -rp "   CODE_DIR [$default_code]: " input_code
    local code_dir="${input_code:-$default_code}"

    if [[ ! -d "$code_dir" ]]; then
        echo "   Warning: $code_dir does not exist"
    fi

    echo ""

    # --- OUTPUT_DIR ---
    local default_output="$HOME/Documents/code-html"
    echo "2) OUTPUT_DIR — Directory for generated HTML output"
    read -rp "   OUTPUT_DIR [$default_output]: " input_output
    local output_dir="${input_output:-$default_output}"

    if [[ ! -d "$output_dir" ]]; then
        read -rp "   $output_dir does not exist. Create it? [Y/n] " create_answer
        if [[ ! "$create_answer" =~ ^[Nn] ]]; then
            mkdir -p "$output_dir"
            echo "   Created $output_dir"
        fi
    fi

    echo ""

    # --- EXCLUDE_PROJECTS ---
    echo "3) EXCLUDE_PROJECTS — Projects to exclude (space-separated names, or leave empty)"
    read -rp "   EXCLUDE_PROJECTS []: " input_exclude
    local exclude_projects="${input_exclude:-}"

    echo ""

    # --- SIDEBAR_STYLE ---
    echo "4) SIDEBAR_STYLE — Sidebar layout: 'tree' (nested folders) or 'flat' (file paths)"
    read -rp "   SIDEBAR_STYLE [tree]: " input_sidebar
    local sidebar_style="${input_sidebar:-tree}"

    echo ""

    # --- HTTP_PORT ---
    echo "5) HTTP_PORT — Port for the web server"
    read -rp "   HTTP_PORT [8000]: " input_port
    local http_port="${input_port:-8000}"

    echo ""

    # --- Write .env ---
    cat > "$SCRIPT_DIR/.env" << EOF
# code-docs configuration
# Generated by ./code-docs.sh setup

# Directory containing source code projects with .md files
CODE_DIR="$code_dir"

# Directory where generated HTML docs will be written
OUTPUT_DIR="$output_dir"

# Projects to exclude from documentation (space-separated directory names)
EXCLUDE_PROJECTS="$exclude_projects"

# Sidebar display style: "tree" (nested folders) or "flat" (file paths as flat links)
SIDEBAR_STYLE="$sidebar_style"

# HTTP port for the web server
HTTP_PORT="$http_port"
EOF

    echo "Configuration saved to .env:"
    echo "  CODE_DIR=$code_dir"
    echo "  OUTPUT_DIR=$output_dir"
    [[ -n "$exclude_projects" ]] && echo "  EXCLUDE_PROJECTS=$exclude_projects"
    echo "  SIDEBAR_STYLE=$sidebar_style"
    echo "  HTTP_PORT=$http_port"
}

cmd_up() {
    local clean_mode=false

    for arg in "$@"; do
        [[ "$arg" == "--clean" ]] && clean_mode=true
    done

    # Auto-setup if no .env
    if [[ ! -f "$SCRIPT_DIR/.env" ]]; then
        echo "No .env found. Running setup first..."
        echo ""
        cmd_setup
        echo ""
    fi

    load_env
    check_deps || exit 1

    if container_running; then
        echo "code-docs is already running."
        echo "Use './code-docs.sh status' to check state or './code-docs.sh down' to stop."
        return 0
    fi

    if [[ "$clean_mode" == true ]]; then
        if [[ -z "${OUTPUT_DIR:-}" ]]; then
            echo "Error: OUTPUT_DIR is not set. Run './code-docs.sh setup' first."
            exit 1
        fi
        if [[ ! -d "$OUTPUT_DIR" ]]; then
            echo "Output directory does not exist, nothing to clean."
        else
            echo "Cleaning $OUTPUT_DIR..."
            find "$OUTPUT_DIR" -mindepth 1 -delete
        fi
        echo ""
    fi

    echo "Starting code-docs..."
    run_compose up -d --build

    local port="${HTTP_PORT:-8000}"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "Open in browser:  http://localhost:$port/index.html"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Commands:"
    echo "  View logs:   ./code-docs.sh logs"
    echo "  Stop:        ./code-docs.sh down"
    echo "  Status:      ./code-docs.sh status"
}

cmd_down() {
    load_env || true
    check_deps || exit 1
    echo "Stopping code-docs..."
    run_compose down
}

cmd_status() {
    echo "=== code-docs status ==="
    echo ""

    check_deps || exit 1

    run_compose ps

    echo ""

    if load_env; then
        echo "Configuration:"
        echo "  CODE_DIR:   ${CODE_DIR:-not set}"
        echo "  OUTPUT_DIR: ${OUTPUT_DIR:-not set}"
        echo "  HTTP_PORT:  ${HTTP_PORT:-8000}"
        [[ -n "${EXCLUDE_PROJECTS:-}" ]] && echo "  EXCLUDE_PROJECTS: $EXCLUDE_PROJECTS"
        echo "  SIDEBAR_STYLE: ${SIDEBAR_STYLE:-tree}"

        # Heartbeat
        if [[ -f "${OUTPUT_DIR:-}/_heartbeat.js" ]]; then
            local hb_ts
            hb_ts=$(sed -n 's/.*= *\([0-9]*\).*/\1/p' "$OUTPUT_DIR/_heartbeat.js" 2>/dev/null)
            if [[ -n "$hb_ts" ]]; then
                local now
                now=$(date +%s)
                local age=$(( now - hb_ts ))
                local age_str
                if [[ $age -lt 60 ]]; then
                    age_str="just now"
                elif [[ $age -lt 3600 ]]; then
                    age_str="$(( age / 60 )) minutes ago"
                elif [[ $age -lt 86400 ]]; then
                    age_str="$(( age / 3600 )) hours ago"
                else
                    age_str="$(( age / 86400 )) days ago"
                fi
                echo ""
                echo "Last heartbeat: $age_str"
            fi
        fi

        # Last build
        if [[ -f "${OUTPUT_DIR:-}/_lastbuild.js" ]]; then
            local build_ts
            build_ts=$(sed -n 's/.*= *\([0-9]*\).*/\1/p' "$OUTPUT_DIR/_lastbuild.js" 2>/dev/null)
            if [[ -n "$build_ts" ]]; then
                local now
                now=$(date +%s)
                local age=$(( now - build_ts ))
                local age_str
                if [[ $age -lt 60 ]]; then
                    age_str="just now"
                elif [[ $age -lt 3600 ]]; then
                    age_str="$(( age / 60 )) minutes ago"
                elif [[ $age -lt 86400 ]]; then
                    age_str="$(( age / 3600 )) hours ago"
                else
                    age_str="$(( age / 86400 )) days ago"
                fi
                echo "Last build:     $age_str"
            fi
        fi
    else
        echo "No .env found. Run './code-docs.sh setup' to configure."
    fi
}

cmd_logs() {
    check_deps || exit 1
    run_compose logs -f
}

cmd_help() {
    cat << 'USAGE'
Usage: ./code-docs.sh <command> [options]

Commands:
  setup          Interactive .env configuration wizard
  up             Start the Docker container (auto-runs setup if no .env)
  up --clean     Clean all output files, then start the Docker container
  down           Stop the Docker container
  status         Show container state and configuration
  logs           Follow container logs (Ctrl+C to stop)
  help           Show this help message

Examples:
  ./code-docs.sh setup          # First-time setup
  ./code-docs.sh up             # Start (builds docs automatically on startup)
  ./code-docs.sh up --clean     # Remove all output, then start fresh
  ./code-docs.sh status         # Check if container is running
  ./code-docs.sh logs           # View live log output
  ./code-docs.sh down           # Stop everything
USAGE
}

# --- Main dispatch ---

case "${1:-}" in
    setup)
        cmd_setup
        ;;
    up)
        cmd_up "${@:2}"
        ;;
    down)
        cmd_down
        ;;
    status)
        cmd_status
        ;;
    logs)
        cmd_logs
        ;;
    help|--help|-h)
        cmd_help
        ;;
    *)
        cmd_help
        ;;
esac
