#!/bin/bash
# code-docs.sh - Entry-point for the code-docs build system
#
# Usage:
#   ./code-docs.sh setup                Interactive .env wizard
#   ./code-docs.sh up                   Start watcher (auto-setup if no .env)
#   ./code-docs.sh up --build           Full build before starting watcher
#   ./code-docs.sh up --clean           Clean build before starting watcher
#   ./code-docs.sh up --serve           Start watcher + HTTP server on localhost:8000
#   ./code-docs.sh up --serve --build   Build, then start watcher + server
#   ./code-docs.sh down                 Stop watcher (and server if running)
#   ./code-docs.sh status               Show watcher state
#   ./code-docs.sh help                 Usage info

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd -P)"
SESSION_NAME="code-docs"

# --- Helper functions ---

load_env() {
    if [[ -f "$SCRIPT_DIR/.env" ]]; then
        source "$SCRIPT_DIR/.env"
        export PATH="${EXTRA_PATH:+$EXTRA_PATH:}$PATH"
        return 0
    fi
    return 1
}

check_deps() {
    local missing=()
    local serve_mode=false

    # Check if --serve flag is present in arguments
    for arg in "$@"; do
        [[ "$arg" == "--serve" ]] && serve_mode=true
    done

    # Required deps for watcher
    for cmd in pandoc fswatch tmux; do
        if ! command -v "$cmd" &>/dev/null; then
            missing+=("$cmd")
        fi
    done

    # Python required only for --serve
    if [[ "$serve_mode" == true ]] && ! command -v python3 &>/dev/null; then
        missing+=("python3")
    fi

    if [[ ${#missing[@]} -gt 0 ]]; then
        echo "Missing dependencies: ${missing[*]}"
        echo ""
        if command -v brew &>/dev/null; then
            echo "  Install with: brew install ${missing[*]}"
        else
            echo "  Homebrew not found. Install Homebrew first (https://brew.sh),"
            echo "  then run: brew install ${missing[*]}"
        fi
        return 1
    fi
    return 0
}

session_exists() {
    tmux has-session -t "$SESSION_NAME" 2>/dev/null
}

# --- Subcommand functions ---

cmd_setup() {
    echo "=== code-docs setup ==="
    echo ""

    if [[ -f "$SCRIPT_DIR/.env" ]]; then
        echo "Current .env configuration:"
        echo ""
        while IFS= read -r line; do
            # Show non-comment, non-empty lines
            if [[ -n "$line" && "$line" != \#* ]]; then
                echo "  $line"
            fi
        done < "$SCRIPT_DIR/.env"
        echo ""
        read -rp "Reconfigure? [y/N] " answer
        if [[ ! "$answer" =~ ^[Yy] ]]; then
            echo "Keeping existing configuration."
            return 0
        fi
        echo ""
    fi

    # --- EXTRA_PATH ---
    local suggested_path=""
    local platform_hint=""
    if [[ -d "/opt/homebrew/bin" ]]; then
        suggested_path="/opt/homebrew/bin"
        platform_hint="Apple Silicon Mac detected"
    elif [[ -x "/usr/local/bin/brew" ]]; then
        suggested_path="/usr/local/bin"
        platform_hint="Intel Mac detected"
    else
        suggested_path=""
        platform_hint="No Homebrew detected (Linux/other)"
    fi

    echo "1) EXTRA_PATH — Additional PATH for tools (pandoc, fswatch)"
    if [[ -n "$suggested_path" ]]; then
        echo "   $platform_hint → suggesting: $suggested_path"
    else
        echo "   $platform_hint → suggesting: (empty)"
    fi
    read -rp "   EXTRA_PATH [$suggested_path]: " input_path
    local extra_path="${input_path:-$suggested_path}"

    echo ""

    # --- CODE_DIR ---
    local default_code="$HOME/Documents/code"
    echo "2) CODE_DIR — Directory containing source code projects"
    read -rp "   CODE_DIR [$default_code]: " input_code
    local code_dir="${input_code:-$default_code}"

    if [[ ! -d "$code_dir" ]]; then
        echo "   Warning: $code_dir does not exist"
    fi

    echo ""

    # --- OUTPUT_DIR ---
    local default_output="$HOME/Documents/code-html"
    echo "3) OUTPUT_DIR — Directory for generated HTML output"
    read -rp "   OUTPUT_DIR [$default_output]: " input_output
    local output_dir="${input_output:-$default_output}"

    if [[ ! -d "$output_dir" ]]; then
        read -rp "   $output_dir does not exist. Create it? [Y/n] " create_answer
        if [[ ! "$create_answer" =~ ^[Nn] ]]; then
            mkdir -p "$output_dir"
            echo "   Created $output_dir"
        fi
    fi

    echo ""

    # --- Write .env ---
    cat > "$SCRIPT_DIR/.env" << EOF
# code-docs configuration
# Generated by ./code-docs.sh setup

# Directory containing source code projects with .md files
CODE_DIR="$code_dir"

# Directory where generated HTML docs will be written
OUTPUT_DIR="$output_dir"

# Additional PATH entries (e.g. Homebrew bin directory)
# Apple Silicon: /opt/homebrew/bin
# Intel Mac:     /usr/local/bin
# Linux:         (leave empty or omit)
EXTRA_PATH="$extra_path"
EOF

    echo "Configuration saved to .env:"
    echo "  CODE_DIR=$code_dir"
    echo "  OUTPUT_DIR=$output_dir"
    echo "  EXTRA_PATH=$extra_path"
}

cmd_up() {
    local flag="${1:-}"
    local flag2="${2:-}"
    local serve=false
    local build_mode=""

    # Parse flags (support --serve alone or combined with --build/--clean)
    for arg in "$flag" "$flag2"; do
        case "$arg" in
            --serve) serve=true ;;
            --clean) build_mode="clean" ;;
            --build) build_mode="build" ;;
        esac
    done

    # Auto-setup if no .env
    if [[ ! -f "$SCRIPT_DIR/.env" ]]; then
        echo "No .env found. Running setup first..."
        echo ""
        cmd_setup
        echo ""
    fi

    load_env

    if ! check_deps "$flag" "$flag2"; then
        exit 1
    fi

    if session_exists; then
        echo "Watcher is already running (tmux session: $SESSION_NAME)."
        echo "Use './code-docs.sh status' to check state or './code-docs.sh down' to stop."
        return 0
    fi

    # Pre-build if requested
    if [[ "$build_mode" == "clean" ]]; then
        echo "Running clean build..."
        "$SCRIPT_DIR/build-docs.sh" --clean
        echo ""
    elif [[ "$build_mode" == "build" ]]; then
        echo "Running full build..."
        "$SCRIPT_DIR/build-docs.sh"
        echo ""
    fi

    # Start watcher (with or without server)
    if [[ "$serve" == true ]]; then
        local port="${HTTP_PORT:-8000}"

        # Create tmux session with watcher
        tmux new-session -d -s "$SESSION_NAME" "$SCRIPT_DIR/watch-docs.sh"

        # Add http.server in a split pane
        tmux split-window -t "$SESSION_NAME" -h "cd '$OUTPUT_DIR' && python3 -m http.server $port"

        # Balance panes (50/50 split)
        tmux select-layout -t "$SESSION_NAME" even-horizontal

        echo "Watcher and server started (tmux session: $SESSION_NAME)."
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "Open in browser:  http://localhost:$port/index.html"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "Commands:"
        echo "  View logs:     tmux attach -t $SESSION_NAME"
        echo "  Stop both:     ./code-docs.sh down"
        echo "  Check status:  ./code-docs.sh status"
    else
        # Original behavior: watcher only
        tmux new-session -d -s "$SESSION_NAME" "$SCRIPT_DIR/watch-docs.sh"

        echo "Watcher started (tmux session: $SESSION_NAME)."
        echo ""
        echo "  Check status:  ./code-docs.sh status"
        echo "  View output:   tmux attach -t $SESSION_NAME"
        echo "  Stop watcher:  ./code-docs.sh down"
    fi
}

cmd_down() {
    if session_exists; then
        tmux kill-session -t "$SESSION_NAME"
        echo "Watcher stopped."
    else
        echo "Watcher is not running."
    fi
}

cmd_status() {
    echo "=== code-docs status ==="
    echo ""

    # Watcher state
    if session_exists; then
        echo "Watcher: running (tmux session: $SESSION_NAME)"

        # Check if HTTP server is running in the session
        if load_env; then
            local port="${HTTP_PORT:-8000}"
            if pgrep -f "python.*http.server.*$port" > /dev/null 2>&1; then
                echo "Server:  http://localhost:$port"
            fi
        fi
    else
        echo "Watcher: stopped"
    fi

    # Configuration and timestamps
    if load_env; then
        echo ""
        echo "Configuration:"
        echo "  CODE_DIR:   $CODE_DIR"
        echo "  OUTPUT_DIR: $OUTPUT_DIR"
        if [[ -n "${EXTRA_PATH:-}" ]]; then
            echo "  EXTRA_PATH: $EXTRA_PATH"
        fi

        # Heartbeat
        if [[ -f "$OUTPUT_DIR/_heartbeat.js" ]]; then
            local hb_ts
            hb_ts=$(sed -n 's/.*= *\([0-9]*\).*/\1/p' "$OUTPUT_DIR/_heartbeat.js" 2>/dev/null)
            if [[ -n "$hb_ts" ]]; then
                local now
                now=$(date +%s)
                local age=$(( now - hb_ts ))
                local age_str
                if [[ $age -lt 60 ]]; then
                    age_str="just now"
                elif [[ $age -lt 3600 ]]; then
                    age_str="$(( age / 60 )) minutes ago"
                elif [[ $age -lt 86400 ]]; then
                    age_str="$(( age / 3600 )) hours ago"
                else
                    age_str="$(( age / 86400 )) days ago"
                fi
                echo ""
                echo "Last heartbeat: $age_str"
            fi
        fi

        # Last build
        if [[ -f "$OUTPUT_DIR/_lastbuild.js" ]]; then
            local build_ts
            build_ts=$(sed -n 's/.*= *\([0-9]*\).*/\1/p' "$OUTPUT_DIR/_lastbuild.js" 2>/dev/null)
            if [[ -n "$build_ts" ]]; then
                local now
                now=$(date +%s)
                local age=$(( now - build_ts ))
                local age_str
                if [[ $age -lt 60 ]]; then
                    age_str="just now"
                elif [[ $age -lt 3600 ]]; then
                    age_str="$(( age / 60 )) minutes ago"
                elif [[ $age -lt 86400 ]]; then
                    age_str="$(( age / 3600 )) hours ago"
                else
                    age_str="$(( age / 86400 )) days ago"
                fi
                echo "Last build:     $age_str"
            fi
        fi
    else
        echo ""
        echo "No .env found. Run './code-docs.sh setup' to configure."
    fi
}

cmd_help() {
    cat << 'USAGE'
Usage: ./code-docs.sh <command> [options]

Commands:
  setup          Interactive .env configuration wizard
  up             Start the file watcher (auto-runs setup if no .env)
  up --build     Run a full build, then start the watcher
  up --clean     Clean build (remove all output), then start the watcher
  up --serve     Start watcher + HTTP server on localhost:8000
  down           Stop the file watcher (and server if running)
  status         Show watcher state and configuration
  help           Show this help message

Examples:
  ./code-docs.sh setup              # First-time setup
  ./code-docs.sh up                 # Start watching for changes
  ./code-docs.sh up --serve         # Start watcher + local web server
  ./code-docs.sh up --serve --build # Build first, then serve
  ./code-docs.sh status             # Check if watcher/server running
  ./code-docs.sh down               # Stop everything
USAGE
}

# --- Main dispatch ---

case "${1:-}" in
    setup)
        cmd_setup
        ;;
    up)
        cmd_up "${2:-}" "${3:-}"
        ;;
    down)
        cmd_down
        ;;
    status)
        cmd_status
        ;;
    help)
        cmd_help
        ;;
    *)
        cmd_help
        ;;
esac
